# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb_tp3:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer_tp3:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  
  # flyway:
  #   image: flyway/flyway
  #   command: ["-url=jdbc:mariadb://mariadb:3306/bd_imagenes", "-user=root", "-password=example", "migrate"]
  #   volumes:
  #      - ./sql:/flyway/sql
  #   depends_on:
  #      - mariadb
  #   links:
  #      - mariadb
  #   networks:
  #     - red_ej2
