apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webserver
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver

  template:
    metadata:
      labels: # Todas las etiquetas son privadas, por la falta de prefijo.
        app: webserver
        tier: webserver

    spec:
      containers:
      - name: webserver
        image: leoduville5/tp2-ej3-webserver:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        env:
        - name: "PORT"
          value: "8080"

      #   volumeMounts:
      #   - name: maestro-secret-volume
      #     mountPath: /app/
      #     readOnly: true
      # volumes:
      # - name: maestro-secret-volume
      #   secret:
      #     secretName: maestro-secrets

      # El siguiente código indica que el pod puede ser desplegado en nodos de tipo spot.
      tolerations:
      - key: instance_type
        operator: Equal
        value: spot
        effect: NoSchedule
      affinity:
        # El siguiente código permite que el pod sea desplegado en un nodo matcheado por 'matchExpressions'.
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                - devops