version: '3'
services:
  extremo:
    image: extremo:latest
    ports:
      - 5001:8080
    volumes:
      - ./archivos:/app/archivos
    networks:
      - mi-red


  extremo2:
    image: extremo:latest
    ports:
      - 5002:8080
    volumes:
      - ./archivos2:/app/archivos
    networks:
      - mi-red


networks:
  mi-red:
    external: true
