version: '3'
services:
  worker:
    image: worker:latest
    ports:
      - 5053:8080
    volumes:
      - ../cloud/terraform/terraform.json:/app/terraform.json
    networks:
      - red_ej2

networks:
  red_ej2:
    external: true