version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672   # Port for AMQP communication
      - 15672:15672 # Port for RabbitMQ management panel
    volumes:
      - ./data:/var/lib/rabbitmq # Mount a volume to persist data
    networks:
      - red_ej2

networks:
  red_ej2:
    external: true      
    # networks:
    #   - network1
    # healthcheck:
    #   test: ["CMD", "rabbitmq-diagnostics", "check_running"]
    #   interval: 10s
    #   retries: 10

#   divide:
#     image: marcos1as/divide
#     ports:
#       - 8080:80
#     depends_on:
#       rabbitmq:
#         condition: service_healthy
#     networks:
#       - network1
#     environment:
#       AMQP_URL: amqp://guest:guest@divide:5672

#   worker:
#     image: marcos1as/worker
#     depends_on:
#       rabbitmq:
#         condition: service_healthy
#     networks:
#     -  network1
#     environment:
#       AMQP_URL: amqp://guest:guest@worker:5672


#   unifier:
#     image: marcos1as/unifier
#     depends_on:
#       rabbitmq:
#         condition: service_healthy
#     networks:
#     -  network1
#     environment:
#       AMQP_URL: amqp://guest:guest@unifier:5672


# networks:
#   network1:
#     external: true
