name: Spring Pipeline 

on:
  push:
    branches:
      - main


jobs:
  setup-stage:
    outputs:
      env-name: ${{ steps.env-name.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Name
        id: env-name
        run: echo "env=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  dependencies:
    needs: [setup-stage] 
    
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ needs.setup-stage.outputs.env-name }}
      
    env:
      # secrets -> https://github.com/dpetrocelli/unlu-content/settings/secrets/actions
      
      name: ${{ needs.setup-stage.outputs.env-name }}
      PORT: ${{ secrets.PORT }}
      CLIENT_ORIGIN_URL: ${{ secrets.CLIENT_ORIGIN_URL }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
    
    steps:
      # STEP 0 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # STEP 2 - Build JAR based on env vars (taken from secrets) 
      - name: Run ls command
        working-directory: TP 2/Ejercicio 2/ejercicio b
        run: |
          ls -lah
          
      - name: Run npm install commands
        working-directory: TP 2/Ejercicio 2/ejercicio b
        run: |
          sudo apt-get install maven
        
      # - name: Run npm outdated
      #   working-directory: sd/main_concepts/09_nodejs_pipeline
      #   run: |
      #     npm outdated
    
  build:
    needs: [setup-stage, dependencies] 
    
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ needs.setup-stage.outputs.env-name }}
      
    env:
      # secrets -> https://github.com/dpetrocelli/unlu-content/settings/secrets/actions
      
      name: ${{ needs.setup-stage.outputs.env-name }}
      PORT: ${{ secrets.PORT }}
      CLIENT_ORIGIN_URL: ${{ secrets.CLIENT_ORIGIN_URL }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        #working-directory: sd/main_concepts/09_nodejs_pipeline
        uses: docker/build-push-action@v4
        with:
          context: TP 2/Ejercicio 2/ejercicio b
          file: TP 2/Ejercicio 2/ejercicio b/demo/Dockerfile
          push: true
          tags: marcos1as/sobelDemo:latest
      
      - name: Run docker image
        working-directory: TP 2/Ejercicio 2/ejercicio b
        run: |
          docker image ls
